services:
  # 1. O Banco de Dados (localmente no Docker)
  database:
    image: mongo:6.0
    container_name: nutritionCalendar_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # 2. O Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: nutritionCalendar_backend
    depends_on:
      - database
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

  # 3. O Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: nutritionCalendar_frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:5173"
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
